[package]
name = "flut"
version = "0.1.0"
authors = ["luxn"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_yaml = "0.8.7"
serde_json = "1.0.33"
serde_cbor = "0.9.0"
chrono = { version = "0.4", features = ["serde"] }

